[package]
name = "rust_project"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = "3.0.1"
tokio = { version = "1.38.0", features = ["full"] }
thiserror = "1.0"

[dev-dependencies]
poem = { version = "3.0.1", features = ["test"] } 


